- name: Add PPA
  sudo: yes
  apt_repository: repo={{item}}
  with_items:
    - ppa:nginx/stable
    - ppa:chris-lea/node.js
    - ppa:git-core/ppa
    - ppa:pi-rho/dev


- name: Install packages
  sudo: yes
  apt: pkg={{ item }} state=installed update_cache=yes
  with_items:
      - git
      - vim
      - tmux
      - nodejs
      - npm
      - nginx

- name: Create symlink for nodejs
  sudo: yes
  file:
    src: /usr/bin/nodejs 
    dest: /usr/bin/node
    state: link

- name: Install global npm modules
  sudo: yes
  npm: name={{ item }} global=yes
  with_items:
      - standard # javascript standard style
      - node-inspector

- name: Create symlink for .vimrc
  file:
    src: /bdyp/my/dev_env/.vimrc
    dest: ~/.vimrc
    state: link

- name: install vundle
  git: repo=https://github.com/VundleVim/Vundle.vim.git
       dest=~/.vim/bundle/Vundle.vim

# - name: install vundle plugin
# #   shell: echo | echo | vim -c PluginInstall -c qa &>/dev/null
#   local_action: ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -i /Users/junshen/test/vagrant3/.vagrant/machines/default/virtualbox/private_key vagrant@127.0.0.1 -p 2222 -t 'echo | echo | vim +PluginInstall +qall &>/dev/null' 
#   # shell: vim -V -c PluginInstall -c qall
#   # shell: vim -V -E -s -c "source ~/.vimrc" -c PluginInstall -c qa &>/dev/null
#   ignore_errors: yes
