#! /bin/bash

# install home brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install ansible
brew install ansible

# run setup playbook
ansible-playbook -i "localhost," ./mothership.yml
