#! /bin/bash

# install home brew
ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"

# install ansible
/usr/local/bin/brew install ansible

# run setup playbook
/usr/local/bin/ansible-playbook -v -i "localhost," ./mothership.yml --extra-vars "ansible_sudo_pass=sj198511"
